export const ENTITY_EXCEPTION_CODE = {
  VALIDATION: 'D1422',
  NOT_FOUND: 'D1404',
  ALREADY_EXISTS: 'D1409',
};

export const GENERAL_EXCEPTION_CODE = {
  BAD_REQUEST: 'D400',
  UNATHORAZED: 'D401',
  ACCESS_DENIED: 'D403',
};
